name: GCP - Create terraform plan and apply for State Infrastructure

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'GCP - Create terraform plan and apply for State Infrastructure'
        required: true
        default: 'gcp/state-infrastructure'

jobs:
  plan-dev:
    name: 'terraform plan dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'gcp/state-infrastructure/'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: GCP Auth
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plandev
        run: terraform plan -no-color -var-file="config/dev/terraform.tfvars"

      - name: Terraform Apply
        id: applydev
        run: terraform apply -auto-approve -var-file="config/dev/terraform.tfvars"